# Generated by Django 4.2.7 on 2024-03-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('floral', 'Floral Decorations'), ('candles', 'Candles and Lanterns'), ('lighting', 'Lighting'), ('signage', 'Custom Signage and Stationery'), ('themed', 'Themed Decor')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='decoration_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
