# Generated by Django 4.2.7 on 2024-03-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0004_license_dob_license_first_name_license_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
