# Generated by Django 4.2.7 on 2024-03-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0007_foodoption_subcategory_alter_foodoption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodoption',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='subcategory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
