# Generated by Django 4.2.7 on 2024-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0008_alter_foodoption_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodoption',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('fusion', 'Fusion Cuisine'), ('international', 'International Mix'), ('gourmet', 'Gourmet Mix'), ('healthy', 'Healthy Mix'), ('regional', 'Regional Mix')], max_length=20, null=True),
        ),
    ]
