# Generated by Django 4.2.7 on 2024-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0010_alter_foodoption_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodoption',
            name='subcategory',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
