# Generated by Django 4.2.7 on 2024-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0011_alter_foodoption_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationoption',
            name='subtype',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
