# Generated by Django 4.2.7 on 2024-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0012_decorationoption_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('wedding_events', 'Wedding Events'), ('pre_wedding_events', 'Pre Wedding Events'), ('post_wedding_events', 'Post Wedding Events')], max_length=40)),
                ('events', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
