# Generated by Django 4.2.7 on 2024-04-06 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0015_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
