# Generated by Django 4.2.7 on 2024-04-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0017_schedulingbookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='booking_count',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='date',
        ),
    ]
