# Generated by Django 4.2.7 on 2024-04-07 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0018_remove_scheduling_booking_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulingBookings',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
