# Generated by Django 4.2.7 on 2024-04-07 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0019_delete_schedulingbookings_scheduling_booking_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('booking_count', models.IntegerField(default=0)),
                ('limit', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='booking_count',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='date',
        ),
    ]
