# Generated by Django 4.2.7 on 2023-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0010_personaldetails_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='perso_fill',
            field=models.BooleanField(default=False),
        ),
    ]
