# Generated by Django 4.2.7 on 2023-11-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0012_personaldetails_religion_personaldetails_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='marital_status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
