# Generated by Django 4.2.7 on 2023-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0014_familydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydetails',
            name='famil_fill',
            field=models.BooleanField(default=False),
        ),
    ]
