# Generated by Django 4.2.7 on 2023-11-05 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony', '0015_familydetails_famil_fill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(max_length=100)),
                ('ug_degree', models.CharField(max_length=100)),
                ('pg_degree', models.CharField(max_length=100)),
                ('doctorate_field', models.CharField(max_length=100)),
                ('college_institution', models.CharField(max_length=100)),
                ('educ_fill', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
