# Generated by Django 4.2.7 on 2023-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0016_educationaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldetails',
            name='grad_year',
            field=models.DateField(default='2023-11-01'),
            preserve_default=False,
        ),
    ]
