# Generated by Django 4.2.7 on 2023-11-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0017_educationaldetails_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='birth_place',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
