# Generated by Django 4.2.7 on 2023-11-05 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony', '0018_personaldetails_birth_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldetails',
            name='doctorate_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='educationaldetails',
            name='pg_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='educationaldetails',
            name='ug_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employerof', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('job_location', models.CharField(blank=True, max_length=100)),
                ('about_job', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('empl_fill', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
