# Generated by Django 4.2.7 on 2023-11-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony', '0019_alter_educationaldetails_doctorate_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_city', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=100)),
                ('current_pin_code', models.CharField(max_length=20)),
                ('willing_to_move', models.CharField(max_length=3)),
                ('additional_comments', models.TextField(blank=True)),
                ('location_photos', models.ImageField(blank=True, null=True, upload_to='location_photos/')),
                ('loca_fill', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
