# Generated by Django 4.2.7 on 2023-11-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0020_locationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
