# Generated by Django 4.2.7 on 2023-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0027_personaldetails_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='matrimony.hobby'),
        ),
    ]
