# Generated by Django 4.2.7 on 2023-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0028_hobby_remove_personaldetails_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, to='matrimony.hobby'),
        ),
    ]
