# Generated by Django 4.2.7 on 2023-11-20 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony', '0036_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='blocked_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='blocked_user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.personaldetails'),
        ),
    ]
