# Generated by Django 4.2.7 on 2023-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0037_blockeduser_blocked_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldetails',
            name='pg_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
