# Generated by Django 4.2.7 on 2024-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destpayment', '0002_alter_packagebooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
