# Generated by Django 4.2.7 on 2024-04-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destpayment', '0007_custompackagebooking_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackagebooking',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
