# Generated by Django 4.2.7 on 2024-04-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destmanager', '0014_rename_events_eventoption_event'),
        ('destpayment', '0008_custompackagebooking_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompackagebooking',
            name='decor_type',
        ),
        migrations.RemoveField(
            model_name='custompackagebooking',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='custompackagebooking',
            name='food_type',
        ),
        migrations.AddField(
            model_name='custompackagebooking',
            name='decor_type',
            field=models.ManyToManyField(to='destmanager.decorationoption'),
        ),
        migrations.AddField(
            model_name='custompackagebooking',
            name='event_type',
            field=models.ManyToManyField(to='destmanager.eventoption'),
        ),
        migrations.AddField(
            model_name='custompackagebooking',
            name='food_type',
            field=models.ManyToManyField(to='destmanager.foodoption'),
        ),
    ]
