# Generated by Django 4.2.7 on 2024-04-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destpayment', '0009_remove_custompackagebooking_decor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackagebooking',
            name='event_datefrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custompackagebooking',
            name='event_dateto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
