# Generated by Django 4.2.7 on 2023-11-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0024_personaldetails_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='linkedin_profile',
            new_name='social_link',
        ),
    ]
