# Generated by Django 4.2.7 on 2023-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0025_rename_linkedin_profile_employmentdetails_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
    ]
