# Generated by Django 4.2.7 on 2023-11-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0026_personaldetails_aadhar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
