# Generated by Django 4.2.7 on 2024-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_eventmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dectype',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='subcategory',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='subtype',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
