# Generated by Django 4.2.3 on 2023-09-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_alter_hobby_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='father',
        ),
        migrations.DeleteModel(
            name='FatherProfile',
        ),
    ]
