# Generated by Django 4.2.7 on 2023-11-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0011_personaldetails_perso_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='religion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='sector',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
