# Generated by Django 4.2.7 on 2023-11-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0021_personaldetails_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='about_you',
            field=models.TextField(blank=True),
        ),
    ]
