# Generated by Django 4.2.7 on 2023-11-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0022_personaldetails_about_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
