# Generated by Django 4.2.7 on 2023-11-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0023_alter_personaldetails_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
