# Generated by Django 4.2.7 on 2023-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0029_alter_personaldetails_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetails',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
