# Generated by Django 4.2.7 on 2023-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0038_alter_educationaldetails_pg_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldetails',
            name='doctorate_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
