# Generated by Django 4.2.7 on 2023-11-25 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0037_blockeduser_blocked_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matint', '0004_rename_user_interest_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressed_interest_by', to=settings.AUTH_USER_MODEL)),
                ('interested_user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.personaldetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressed_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
